name: Update status

on:
  schedule:
    - cron: "30 3 * * 1-5" # 12:30 in UTC+9

jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14.4"
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile
      - run: yarn run update
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_OAUTH_TOKEN: ${{ secrets.TWITTER_OAUTH_TOKEN }}
          TWITTER_OAUTH_SECRET: ${{ secrets.TWITTER_OAUTH_SECRET }}
